import { Publication } from "../schemas";

export const mockPublications: Publication[] = [
    {
        id: "550e8400-e29b-41d4-a716-446655440000",
        title: "Welcome to Social Assistant",
        content:
            "This is my first automated post generated by n8n. Excited to share my thoughts with the LinkedIn community! #SocialMedia #Automation",
        status: "draft",
        platform: "linkedin",
        scheduledAt: null,
        publishedAt: null,
        createdAt: new Date(),
        updatedAt: new Date(),
        isDeleted: false,
    },
    {
        id: "660e8400-e29b-41d4-a716-446655440001",
        title: "Tech Innovation Insights",
        content:
            "Exploring the latest trends in AI and automation. The future of work is here, and it's more exciting than ever. What are your thoughts on how AI is transforming our industry?",
        status: "scheduled",
        platform: "linkedin",
        scheduledAt: new Date(Date.now() + 24 * 60 * 60 * 1000), // Tomorrow
        publishedAt: null,
        createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000), // 2 days ago
        updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000), // 1 day ago
        isDeleted: false,
    },
    {
        id: "770e8400-e29b-41d4-a716-446655440002",
        title: "Weekly Reflection",
        content:
            "Another week of learning and growth. Grateful for the opportunities to connect with amazing professionals. What was your highlight this week?",
        status: "published",
        platform: "linkedin",
        scheduledAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000), // 7 days ago
        publishedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000), // 5 days ago
        createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000), // 10 days ago
        updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000), // 5 days ago
        isDeleted: false,
    },
    {
        id: "880e8400-e29b-41d4-a716-446655440003",
        title: "Industry Insights",
        content:
            "Just read an interesting article about the future of remote work. The hybrid model seems to be the new standard. How is your company adapting?",
        status: "published",
        platform: "linkedin",
        scheduledAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000), // 14 days ago
        publishedAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000), // 12 days ago
        createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000), // 15 days ago
        updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000), // 1 day ago (when deleted)
        isDeleted: true,
    },
];

